# embed.cmake - bundle the panel sources into one self-contained page and
# emit it as C: `const char index_html[]`, NUL-terminated, in .rodata.
# Copyright (c) 2026 Scott Wiederhold <s.e.wiederhold@gmail.com>
# SPDX-License-Identifier: MIT
#
# Run by CMakeLists.txt as a custom command:
#   cmake -DUI_DIR=<src/ui> -DOUT_HTML=<bundled index.html> -DOUT_C=<ui_blob.c>
#         -P embed.cmake
#
# panel.css and panel.js are inlined where index.html links them, so the
# daemon serves exactly one response with no external assets (the token
# placeholder in panel.js survives untouched for main.c to substitute).
# The bundled page is also written out (OUT_HTML) for inspection; it is
# what tools/devserver.py --bundle serves.

foreach(v UI_DIR OUT_HTML OUT_C)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "embed.cmake: ${v} not set")
  endif()
endforeach()

file(READ "${UI_DIR}/index.html" HTML)
file(READ "${UI_DIR}/panel.css" CSS)
file(READ "${UI_DIR}/panel.js" JS)

set(CSS_TAG "<link rel=\"stylesheet\" href=\"panel.css\" />")
set(JS_TAG "<script src=\"panel.js\"></script>")
foreach(tag CSS_TAG JS_TAG)
  string(FIND "${HTML}" "${${tag}}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "embed.cmake: index.html lacks the marker ${${tag}}")
  endif()
endforeach()
string(REPLACE "${CSS_TAG}" "<style>\n${CSS}</style>" HTML "${HTML}")
string(REPLACE "${JS_TAG}" "<script>\n${JS}</script>" HTML "${HTML}")
file(WRITE "${OUT_HTML}" "${HTML}")

# Byte array, 16 per line, plus the terminator.
file(READ "${OUT_HTML}" HEX HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," HEX "${HEX}")
set(B "0x[0-9a-f][0-9a-f],")
string(REGEX REPLACE "(${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B})"
       "\\1\n" HEX "${HEX}")
file(WRITE "${OUT_C}"
"/* Generated by src/ui/embed.cmake from src/ui/ - do not edit. */
#include \"ui.h\"

const char index_html[] = {
${HEX}0x00
};
")
