/*
 * ui.c - forgectrl: the embedded web UI
 * Copyright (c) 2026 Scott Wiederhold <s.e.wiederhold@gmail.com>
 * SPDX-License-Identifier: MIT
 *
 * Single-page machine control panel, served at "/" and self-contained
 * (inline CSS/JS + inline-SVG logo, no external assets, ES5 only).
 * Visual identity follows the OpenGlow project (community.openglow.org):
 * navy header carrying the OpenGlow starburst wordmark, light content
 * area, blue actions, laser red reserved for the brand accent and
 * fault states. Hash-routed tabs:
 *
 *   #status   landing page - live operational status (motion state and
 *             position, cooling and fans, safety switches, system
 *             summary) plus a scaled lid snapshot that switches to the
 *             live MJPEG stream on demand
 *   #machine  shared machine settings (homing method + calibration)
 *   #gfcloud  Glowforge cloud overrides (identity, homing session)
 *   #grbl     GRBL-mode settings (controller info; tunables land here
 *             as the driver exposes them)
 *
 * State flows through GET/POST /settings, GET /status (machine
 * telemetry) and GET /cam/status. The design intent: every machine
 * tunable - shared, cloud-override, and GRBL-mode - gets a home in one
 * of these tabs as it appears.
 */
#include "ui.h"

const char index_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ForgeFIRM</title>"
"<style>"
":root{--navy:#2b2b5e;--red:#e8262a;--blue:#0088cc;--bg:#f0f1f4;"
"--card:#fff;--line:#dde0e6;--txt:#222;--dim:#767a82;--ok:#3d854d;"
"--warn:#c7760a}"
"*{box-sizing:border-box}"
"body{margin:0;font-family:system-ui,-apple-system,'Segoe UI',Roboto,"
"sans-serif;background:var(--bg);color:var(--txt);font-size:14px}"
"header{background:var(--navy)}"
".hrow{max-width:820px;margin:0 auto;padding:12px 20px;display:flex;"
"align-items:center;gap:14px}"
".appname{color:#fff;font-size:19px;font-weight:600;letter-spacing:.3px;"
"border-left:1px solid rgba(255,255,255,.25);padding-left:14px}"
"#host{color:rgba(255,255,255,.55);font-size:13px;margin-left:auto}"
"nav{background:var(--card);border-bottom:1px solid var(--line)}"
".nrow{max-width:820px;margin:0 auto;padding:0 20px;display:flex;gap:2px}"
"nav a{padding:10px 14px;color:var(--dim);text-decoration:none;"
"border-bottom:2px solid transparent;margin-bottom:-1px}"
"nav a.on{color:var(--navy);font-weight:600;border-color:var(--red)}"
"nav a:hover{color:var(--navy)}"
"main{max-width:820px;margin:0 auto;padding:6px 20px 12px}"
"section{display:none}section.on{display:block}"
".card{background:var(--card);border:1px solid var(--line);"
"border-radius:8px;padding:16px 18px;margin:14px 0;"
"box-shadow:0 1px 2px rgba(0,0,0,.04)}"
".card h2{font-size:12.5px;margin:0 0 10px;color:var(--navy);"
"font-weight:700;text-transform:uppercase;letter-spacing:.9px}"
".grid2{display:grid;grid-template-columns:1fr 1fr;gap:0 28px}"
".hint{color:var(--dim);font-size:12.5px;line-height:1.55;margin:10px 0 0}"
".hint a{color:var(--blue)}"
".row{display:grid;grid-template-columns:190px 1fr;gap:8px 12px;"
"align-items:center;margin:8px 0}"
".row label{color:var(--txt)}"
".row .u{color:var(--dim);font-size:12px;margin-left:6px}"
"input,select{background:#fff;color:var(--txt);border:1px solid #c9cdd4;"
"border-radius:5px;padding:7px 9px;font:inherit;width:100%}"
"input:focus,select:focus{outline:none;border-color:var(--blue)}"
"input::placeholder{color:#a6aab2}"
"button{background:#fff;color:var(--txt);border:1px solid #c9cdd4;"
"border-radius:5px;padding:7px 14px;font:inherit;cursor:pointer}"
"button:hover{border-color:var(--navy)}"
"button.pri{background:var(--blue);border-color:var(--blue);color:#fff;"
"font-weight:600}"
"button.pri:hover{background:#0077b3}"
".btns{margin-top:14px;display:flex;gap:8px;align-items:center;"
"flex-wrap:wrap}"
".msg{font-size:13px;color:var(--blue)}"
"#cam{width:100%;max-width:520px;border-radius:6px;border:1px solid "
"var(--line);display:block;margin:0 auto;background:#e8e9ec;"
"min-height:60px}"
".camwrap{text-align:center}"
".camctl{margin-top:10px;display:flex;gap:8px;justify-content:center}"
"#live.on{background:var(--navy);border-color:var(--navy);color:#fff;"
"font-weight:600}"
".kv{display:flex;justify-content:space-between;gap:12px;padding:6px 2px;"
"border-bottom:1px solid #eceef1;font-size:13.5px}"
".kv:last-child{border-bottom:none}"
".kv span:first-child{color:var(--dim)}"
".kv .mono{font-family:ui-monospace,Consolas,monospace}"
".b-ok{color:var(--ok);font-weight:600}"
".b-run{color:var(--blue);font-weight:600}"
".b-bad{color:var(--red);font-weight:600}"
".b-dim{color:var(--dim)}"
".b-warn{color:var(--warn);font-weight:600}"
"footer{max-width:820px;margin:0 auto;padding:6px 20px 28px;"
"color:var(--dim);font-size:12.5px;text-align:center}"
"footer a{color:var(--blue);text-decoration:none}"
"@media(max-width:620px){.row{grid-template-columns:1fr;gap:3px 0}"
".grid2{grid-template-columns:1fr}}"
"</style></head><body>"

/* OpenGlow-branded header: recreated starburst wordmark + app name */
"<header><div class='hrow'>"
"<svg width='148' height='36' viewBox='0 0 148 36' aria-label='OpenGlow'>"
"<g stroke='#e8262a' stroke-linecap='round'>"
"<line x1='34' y1='8' x2='146' y2='8' stroke-width='1.2'/>"
"<line x1='34' y1='0.5' x2='34' y2='15.5' stroke-width='1.2'/>"
"<line x1='26.5' y1='8' x2='41.5' y2='8' stroke-width='1.2'/>"
"<line x1='28.7' y1='2.7' x2='39.3' y2='13.3' stroke-width='1.1'/>"
"<line x1='39.3' y1='2.7' x2='28.7' y2='13.3' stroke-width='1.1'/>"
"<line x1='31.1' y1='1.1' x2='36.9' y2='14.9' stroke-width='.8'/>"
"<line x1='36.9' y1='1.1' x2='31.1' y2='14.9' stroke-width='.8'/>"
"<line x1='27.1' y1='5.1' x2='40.9' y2='10.9' stroke-width='.8'/>"
"<line x1='40.9' y1='5.1' x2='27.1' y2='10.9' stroke-width='.8'/>"
"</g>"
"<circle cx='34' cy='8' r='2' fill='#e8262a'/>"
"<text x='0' y='31' font-size='20' font-family='inherit'>"
"<tspan fill='#fff' font-weight='600'>Open</tspan>"
"<tspan fill='#b9bac9' font-weight='300'>Glow</tspan></text>"
"</svg>"
"<span class='appname'>ForgeFIRM</span>"
"<span id='host'></span>"
"</div></header>"
"<nav><div class='nrow'>"
"<a href='#status' id='t-status'>Status</a>"
"<a href='#machine' id='t-machine'>Machine</a>"
"<a href='#gfcloud' id='t-gfcloud'>GF Cloud</a>"
"<a href='#grbl' id='t-grbl'>GRBL</a>"
"</div></nav><main>"

/* ------------------------------------------------------ status tab */
"<section id='s-status'>"
"<div class='card'><h2>Motion</h2><div id='motion'></div></div>"
"<div class='card camwrap'><h2>Lid camera</h2>"
"<img id='cam' alt='lid camera'>"
"<div class='camctl'>"
"<button id='live' onclick='toggleLive()'>Live</button>"
"<button id='snapbtn' onclick='refreshSnap()'>Refresh</button>"
"</div>"
"<p class='hint' id='cammsg'></p>"
"</div>"
"<div class='grid2'>"
"<div class='card'><h2>Cooling</h2><div id='cooling'></div></div>"
"<div class='card'><h2>Switches</h2><div id='switches'></div>"
"<p class='hint'>Closed/OK reads as active. The interlock reads open "
"on machines without the rear plug, and the e-stop sense reads low "
"whenever the machine is moving - the beam is gated by the hardware "
"safety chain regardless.</p></div>"
"</div>"
"<div class='card'><h2>System</h2><div id='statgrid'></div></div>"
"</section>"

/* ----------------------------------------------------- machine tab */
"<section id='s-machine'>"
"<div class='card'><h2>Homing</h2>"
"<div class='row'><label for='homing_mode'>Method</label>"
"<select id='homing_mode'>"
"<option value='none'>Disabled</option>"
"<option value='gfcloud'>Glowforge web service (cameras)</option>"
"<option value='switches'>Limit switches</option>"
"</select></div>"
"<div class='row'><label for='gfcloud_home_x'>Home position X"
"<span class='u'>mm</span></label>"
"<input id='gfcloud_home_x' inputmode='decimal' placeholder='0 (origin)'>"
"</div>"
"<div class='row'><label for='gfcloud_home_y'>Home position Y"
"<span class='u'>mm</span></label>"
"<input id='gfcloud_home_y' inputmode='decimal' placeholder='0 (origin)'>"
"</div>"
"<div class='row'><label for='gfcloud_home_z'>Home position Z"
"<span class='u'>mm</span></label>"
"<input id='gfcloud_home_z' inputmode='decimal' "
"placeholder='top of travel'></div>"
"<p class='hint'>Machine coordinates the head is at after a completed "
"homing cycle. For Glowforge web-service homing that is the factory "
"home corner (back left) with the lens at the hall reference &mdash; "
"leave blank until a measurement says otherwise. To calibrate: home, "
"jog to a known reference, and enter the measured offsets.</p>"
"<div class='btns'><button class='pri' onclick='saveMachine()'>Save"
"</button><span class='msg' id='msg-m'></span></div>"
"</div>"
"</section>"

/* ---------------------------------------------------- gfcloud tab */
"<section id='s-gfcloud'>"
"<div class='card'><h2>Machine identity</h2>"
"<div class='row'><label for='gf_serial'>Serial number</label>"
"<input id='gf_serial' inputmode='numeric' placeholder='(factory fuses)'>"
"</div>"
"<div class='row'><label for='gf_password'>Password</label>"
"<input id='gf_password' type='password' autocomplete='off'></div>"
"<div class='row'><label for='gf_hostname'>Hostname</label>"
"<input id='gf_hostname' placeholder='(factory fuses)'></div>"
"<p class='hint'>Credentials the machine signs in to the Glowforge "
"web service with. Blank fields use the identity burned into the "
"factory fuses &mdash; override only to stand in for another machine "
"(64 hex digit password). Keep credentials secret; they cannot be "
"changed once leaked. A blank password field keeps the current "
"override.</p>"
"<div class='btns'>"
"<button class='pri' onclick='saveIdentity()'>Save</button>"
"<button onclick='clearIdentity()'>Use factory identity</button>"
"<span class='msg' id='msg-i'></span></div>"
"</div>"
"<div class='card'><h2>Homing session</h2>"
"<div class='row'><label for='gfcloud_home_timeout_s'>Session timeout"
"<span class='u'>seconds</span></label>"
"<input id='gfcloud_home_timeout_s' inputmode='numeric' "
"placeholder='300'></div>"
"<p class='hint'>Overall budget for one web-service homing run "
"(sign-in, camera uploads, hunt and corner moves). The controller "
"aborts and alarms past this; 30&ndash;3600.</p>"
"<div class='btns'><button class='pri' onclick='saveSession()'>Save"
"</button><span class='msg' id='msg-s'></span></div>"
"</div>"
"</section>"

/* ------------------------------------------------------- grbl tab */
"<section id='s-grbl'>"
"<div class='card'><h2>Controller</h2><div id='grblinfo'></div>"
"<p class='hint'>The motion controller speaks standard Grbl 1.1 "
"(grblHAL) &mdash; point LightBurn, UGS or cncjs at the connection "
"above and use the sender's device settings ($$) for the numbered "
"GRBL parameters. GRBL-mode tunables will appear on this tab as the "
"controller exposes them.</p>"
"</div>"
"</section>"
"</main>"
"<footer>ForgeFIRM is an <a href='https://community.openglow.org'>"
"OpenGlow</a> project</footer>"

/* ------------------------------------------------------------- js */
"<script>"
"var S={},CS={},M={},liveOn=false,retries=0;"
"function $(i){return document.getElementById(i)}"
"function esc(t){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;')}"

/* hash-routed tabs */
"var TABS=['status','machine','gfcloud','grbl'];"
"function tab(){var h=location.hash.replace('#','');"
"if(TABS.indexOf(h)<0)h='status';"
"for(var i=0;i<TABS.length;i++){var t=TABS[i];"
"$('s-'+t).className=t===h?'on':'';"
"$('t-'+t).className=t===h?'on':''}}"
"window.onhashchange=tab;"

/* camera: scaled snapshot by default, live stream on demand */
"function snapUrl(){return '/cam/snapshot?cam=lid&res=half&t='+Date.now()}"
"function refreshSnap(){if(!liveOn)$('cam').src=snapUrl()}"
"function toggleLive(){liveOn=!liveOn;retries=0;$('cammsg').textContent='';"
"$('live').textContent=liveOn?'Stop':'Live';"
"$('live').className=liveOn?'on':'';"
"$('snapbtn').disabled=liveOn;"
"$('cam').src=liveOn?'/cam/stream?cam=lid&t='+Date.now():snapUrl()}"
"$('cam').onerror=function(){if(!liveOn)return;"
"fetch('/cam/status').then(function(r){return r.json()})"
".then(function(s){if(s.cam==='lid'&&retries++<5){"
"$('cammsg').textContent='stream retrying\\u2026';"
"setTimeout(function(){if(liveOn)$('cam').src='/cam/stream?cam=lid&t='+"
"Date.now()},700)}else{$('cammsg').textContent=s.cam!=='lid'?"
"'stream taken by another viewer ('+s.cam+')':'stream error';"
"toggleLive()}}).catch(function(){"
"$('cammsg').textContent='service unreachable'})};"

/* rendering helpers */
"function kv(k,v,cls){return \"<div class='kv'><span>\"+esc(k)+"
"\"</span><span\"+(cls?\" class='\"+cls+\"'\":'')+'>'+v+'</span></div>'}"
"function txt(k,v,cls){return kv(k,esc(v),cls)}"
"function modeName(m){return m==='gfcloud'?'Glowforge web service':"
"m==='switches'?'Limit switches':'Disabled'}"

/* operational status (/status, 2.5 s poll) */
"function stateBadge(st){var c=st==='idle'?'b-ok':st==='running'?"
"'b-run':st==='disabled'?'b-dim':'b-bad';"
"return txt('State',st,c)}"
"function renderMotion(){var g='';"
"g+=stateBadge(M.state||'unknown');"
"if(M.homed&&M.pos)g+=kv('Position',\"<span class='mono'>X \"+"
"M.pos.x.toFixed(2)+' &nbsp;Y '+M.pos.y.toFixed(2)+' &nbsp;Z '+"
"M.pos.z.toFixed(2)+' mm</span>');"
"else g+=txt('Position','not referenced \\u2014 run a homing cycle',"
"'b-dim');"
"g+=txt('Homed',M.homed?'yes':'no',M.homed?'b-ok':'b-dim');"
"if(typeof M.laser_locked!=='undefined')"
"g+=txt('Laser lockout',M.laser_locked?'locked':'UNLOCKED',"
"M.laser_locked?'b-ok':'b-bad');"
"$('motion').innerHTML=g}"
"function rpm(v){return v>0?v+' rpm':'stopped'}"
"function degc(v){return v>-100?v.toFixed(1)+' \\u00b0C':'\\u2014'}"
"function renderCooling(){if(!M.coolant)return;var g='';"
"g+=txt('Coolant out',degc(M.coolant.down_c));"
"g+=txt('Coolant in',degc(M.coolant.up_c));"
"g+=txt('Pump',M.coolant.pump?'on':'off',M.coolant.pump?'b-ok':'b-warn');"
"g+=txt('TEC',M.coolant.tec?'on':'off','b-dim');"
"if(M.fans){g+=txt('Air assist',rpm(M.fans.air_assist));"
"g+=txt('Exhaust',rpm(M.fans.exhaust));"
"g+=txt('Intake 1',rpm(M.fans.intake_1));"
"g+=txt('Intake 2',rpm(M.fans.intake_2))}"
"$('cooling').innerHTML=g}"
"function sw(k,name,on,off,onCls,offCls){var v=M.switches[k];"
"return txt(name,v?on:off,v?onCls:offCls)}"
"function renderSwitches(){if(!M.switches)return;var g='';"
"g+=sw('lid','Lid','closed','OPEN','b-ok','b-warn');"
"g+=sw('button','Button','pressed','released','b-run','b-dim');"
"g+=sw('interlock','Interlock','closed','open','b-ok','b-dim');"
"g+=sw('head','Head sense','detected','not detected','b-ok','b-dim');"
"g+=sw('estop','E-stop sense','ok','low','b-ok','b-dim');"
"$('switches').innerHTML=g}"
"function renderStat(){var g='';"
"g+=txt('Homing',modeName(S.homing_mode));"
"g+=txt('Identity',S.gf_serial?'Override (S'+S.gf_serial+')':"
"'Factory fuses');"
"g+=kv('Controller',\"<span class='mono'>\"+esc(location.hostname)+"
"':23</span> (Grbl 1.1)');"
"if(CS.running)g+=txt('Camera engine',CS.cam+' camera, '+"
"(CS.fps||0).toFixed(1)+' fps, '+CS.encoder+', '+CS.clients+"
"' viewer'+(CS.clients===1?'':'s'));"
"else g+=txt('Camera engine','idle');"
"$('statgrid').innerHTML=g}"
"function renderGrbl(){var g='';"
"g+=txt('Protocol','Grbl 1.1 (grblHAL)');"
"g+=kv('Connection',\"<span class='mono'>\"+esc(location.hostname)+"
"':23</span>');"
"g+=kv('Camera for LightBurn',\"<span class='mono'>http://\"+"
"esc(location.host)+'/?action=stream</span>');"
"$('grblinfo').innerHTML=g}"

/* settings load/save */
"function fill(){$('homing_mode').value=S.homing_mode||'none';"
"$('gfcloud_home_x').value=S.gfcloud_home_x||'';"
"$('gfcloud_home_y').value=S.gfcloud_home_y||'';"
"$('gfcloud_home_z').value=S.gfcloud_home_z||'';"
"$('gfcloud_home_timeout_s').value=S.gfcloud_home_timeout_s||'';"
"$('gf_serial').value=S.gf_serial||'';"
"$('gf_hostname').value=S.gf_hostname||'';"
"$('gf_password').value='';"
"$('gf_password').placeholder=S.gf_password_set?"
"'(override set \\u2014 blank keeps it)':'(factory fuses)';"
"$('host').textContent=S.hostname||'';"
"renderStat()}"
/* settings go in the query string: empty values (= clear the key)
 * are dropped from form bodies by the HTTP stack */
"function post(pairs,msgId){var q='',k;"
"for(k in pairs)q+=(q?'&':'')+encodeURIComponent(k)+'='+"
"encodeURIComponent(pairs[k]);"
"$(msgId).textContent='saving\\u2026';"
"fetch('/settings?'+q,{method:'POST'})"
".then(function(r){if(!r.ok)return r.text().then(function(t)"
"{throw t});return r.json()})"
".then(function(s){S=s;fill();$(msgId).textContent='saved';"
"setTimeout(function(){$(msgId).textContent=''},2500)})"
".catch(function(e){$(msgId).textContent=String(e||'save failed')})}"
"function saveMachine(){post({homing_mode:$('homing_mode').value,"
"gfcloud_home_x:$('gfcloud_home_x').value.trim(),"
"gfcloud_home_y:$('gfcloud_home_y').value.trim(),"
"gfcloud_home_z:$('gfcloud_home_z').value.trim()},'msg-m')}"
"function saveIdentity(){var p={gf_serial:$('gf_serial').value.trim(),"
"gf_hostname:$('gf_hostname').value.trim()};"
"if($('gf_password').value)p.gf_password=$('gf_password').value.trim();"
"post(p,'msg-i')}"
"function clearIdentity(){post({gf_serial:'',gf_password:'',"
"gf_hostname:''},'msg-i')}"
"function saveSession(){post({gfcloud_home_timeout_s:"
"$('gfcloud_home_timeout_s').value.trim()},'msg-s')}"

/* boot + polling */
"function loadMach(){fetch('/status').then(function(r)"
"{return r.json()}).then(function(m){M=m;renderMotion();"
"renderCooling();renderSwitches()}).catch(function(){})}"
"function loadCam(){fetch('/cam/status').then(function(r)"
"{return r.json()}).then(function(s){CS=s;renderStat()})"
".catch(function(){})}"
"fetch('/settings').then(function(r){return r.json()})"
".then(function(s){S=s;fill()}).catch(function(){});"
"loadMach();setInterval(loadMach,2500);"
"loadCam();setInterval(loadCam,5000);"
"renderGrbl();tab();refreshSnap();"
"</script></body></html>";
