/*
 * ui.c - forgectrl: the embedded web UI
 * Copyright (c) 2026 Scott Wiederhold <s.e.wiederhold@gmail.com>
 * SPDX-License-Identifier: MIT
 *
 * Single-page machine control panel, served at "/" and self-contained
 * (inline CSS/JS + inline-SVG logo, no external assets, ES5 only).
 * Visual identity follows the OpenGlow project (community.openglow.org):
 * navy header carrying the OpenGlow starburst wordmark, light content
 * area, blue actions, laser red reserved for the brand accent and
 * fault states. Hash-routed tabs:
 *
 *   #status   landing page - live operational status (motion state and
 *             position, cooling and fans, safety switches, system
 *             summary) plus a scaled lid snapshot that switches to the
 *             live MJPEG stream on demand
 *   #machine  shared machine settings (display units, homing method +
 *             calibration, cooling tunables)
 *   #gfcloud  Glowforge cloud overrides (identity, homing session)
 *             plus the fuse-identity viewer (modal, on demand)
 *   #grbl     GRBL-mode settings (controller info; tunables land here
 *             as the driver exposes them)
 *   #diag     diagnostics - tools that take the hardware over (the
 *             motion controller is stopped for the duration): cooling
 *             system verification and calibration
 *   #system   firmware slots (A/B boot selection), ForgeFIRM updates,
 *             image install/restore, wireless regulatory region, reboot
 *
 * State flows through GET/POST /settings, GET /status (machine
 * telemetry) and GET /cam/status. The design intent: every machine
 * tunable - shared, cloud-override, and GRBL-mode - gets a home in one
 * of these tabs as it appears.
 *
 * The header identifies the machine by its fuse identity (the factory
 * hostname derived from the burned-in serial) regardless of any cloud
 * identity override. Units are a display-only preference (ui_units):
 * the backend stores metric, conversion happens at the UI edge, and
 * saves post only fields whose display string actually changed.
 */
#include "ui.h"

const char index_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ForgeFIRM</title>"
"<style>"
":root{--navy:#2b2b5e;--red:#e8262a;--blue:#0088cc;--bg:#f0f1f4;"
"--card:#fff;--line:#dde0e6;--txt:#222;--dim:#767a82;--ok:#3d854d;"
"--warn:#c7760a}"
"*{box-sizing:border-box}"
"body{margin:0;font-family:system-ui,-apple-system,'Segoe UI',Roboto,"
"sans-serif;background:var(--bg);color:var(--txt);font-size:14px}"
"header{background:var(--navy)}"
".hrow{max-width:820px;margin:0 auto;padding:12px 20px;display:flex;"
"align-items:center;gap:14px}"
".appname{color:#fff;font-size:19px;font-weight:600;letter-spacing:.3px;"
"border-left:1px solid rgba(255,255,255,.25);padding-left:14px}"
"#host{color:rgba(255,255,255,.55);font-size:13px;margin-left:auto}"
"nav{background:var(--card);border-bottom:1px solid var(--line)}"
".nrow{max-width:820px;margin:0 auto;padding:0 20px;display:flex;gap:2px}"
"nav a{padding:10px 14px;color:var(--dim);text-decoration:none;"
"border-bottom:2px solid transparent;margin-bottom:-1px}"
"nav a.on{color:var(--navy);font-weight:600;border-color:var(--red)}"
"nav a:hover{color:var(--navy)}"
"main{max-width:820px;margin:0 auto;padding:6px 20px 12px}"
"section{display:none}section.on{display:block}"
".card{background:var(--card);border:1px solid var(--line);"
"border-radius:8px;padding:16px 18px;margin:14px 0;"
"box-shadow:0 1px 2px rgba(0,0,0,.04)}"
".card h2{font-size:12.5px;margin:0 0 10px;color:var(--navy);"
"font-weight:700;text-transform:uppercase;letter-spacing:.9px}"
".grid2{display:grid;grid-template-columns:1fr 1fr;gap:0 28px}"
".hint{color:var(--dim);font-size:12.5px;line-height:1.55;margin:10px 0 0}"
".hint a{color:var(--blue)}"
".row{display:grid;grid-template-columns:190px 1fr;gap:8px 12px;"
"align-items:center;margin:8px 0}"
".row label{color:var(--txt)}"
".row .u{color:var(--dim);font-size:12px;margin-left:6px}"
"input,select{background:#fff;color:var(--txt);border:1px solid #c9cdd4;"
"border-radius:5px;padding:7px 9px;font:inherit;width:100%}"
"input:focus,select:focus{outline:none;border-color:var(--blue)}"
"input::placeholder{color:#a6aab2}"
"button{background:#fff;color:var(--txt);border:1px solid #c9cdd4;"
"border-radius:5px;padding:7px 14px;font:inherit;cursor:pointer}"
"button:hover{border-color:var(--navy)}"
"button.pri{background:var(--blue);border-color:var(--blue);color:#fff;"
"font-weight:600}"
"button.pri:hover{background:#0077b3}"
"button:disabled{opacity:.55;cursor:not-allowed}"
".btns{margin-top:14px;display:flex;gap:8px;align-items:center;"
"flex-wrap:wrap}"
".msg{font-size:13px;color:var(--blue)}"
"#cam{width:100%;max-width:520px;border-radius:6px;border:1px solid "
"var(--line);display:block;margin:0 auto;background:#e8e9ec;"
"min-height:60px}"
".camwrap{text-align:center}"
".camctl{margin-top:10px;display:flex;gap:8px;justify-content:center}"
"#live.on{background:var(--navy);border-color:var(--navy);color:#fff;"
"font-weight:600}"
".kv{display:flex;justify-content:space-between;gap:12px;padding:6px 2px;"
"border-bottom:1px solid #eceef1;font-size:13.5px}"
".kv:last-child{border-bottom:none}"
".kv>span:first-child{color:var(--dim)}"
".kv .mono{font-family:ui-monospace,Consolas,monospace}"
".seg{display:flex;gap:8px;flex-wrap:wrap;align-items:center}"
".segbtn{padding:9px 22px;border-radius:6px}"
".segbtn.segon{background:var(--navy);border-color:var(--navy);"
"color:#fff;font-weight:600}"
".segbtn:disabled{opacity:.5;cursor:not-allowed}"
".soon{display:block;font-size:10.5px;font-weight:400;opacity:.85}"
"#locknote{display:none;background:#fdf3e3;border:1px solid #eccb90;"
"color:#7a5a12;border-radius:8px;padding:10px 14px;margin:14px 0;"
"font-size:13px}"
".b-ok{color:var(--ok);font-weight:600}"
".b-run{color:var(--blue);font-weight:600}"
".b-bad{color:var(--red);font-weight:600}"
".b-dim{color:var(--dim)}"
".b-warn{color:var(--warn);font-weight:600}"
"#fusewrap{display:none;position:fixed;left:0;top:0;right:0;bottom:0;"
"background:rgba(20,22,30,.55);z-index:50;align-items:center;"
"justify-content:center}"
"#fusewrap.on{display:flex}"
".fusebox{background:var(--card);border:1px solid var(--line);"
"border-radius:10px;padding:18px 22px;max-width:560px;width:92%;"
"box-shadow:0 8px 30px rgba(0,0,0,.25)}"
".fusebox h2{font-size:12.5px;margin:0 0 10px;color:var(--navy);"
"font-weight:700;text-transform:uppercase;letter-spacing:.9px}"
".brk{word-break:break-all}"
".fwarn{background:#fdf3e3;border:1px solid #eccb90;color:#7a5a12;"
"border-radius:6px;padding:8px 12px;font-size:12.5px;margin:12px 0 0;"
"line-height:1.5}"
"#diaglog{background:#23252b;color:#cfd3da;border-radius:6px;"
"padding:10px 12px;font-family:ui-monospace,Consolas,monospace;"
"font-size:12px;line-height:1.6;max-height:220px;overflow-y:auto;"
"white-space:pre-wrap;margin-top:10px;display:none}"
".bigpass{font-size:15px;font-weight:700;color:var(--ok)}"
".bigfail{font-size:15px;font-weight:700;color:var(--red)}"
"footer{max-width:820px;margin:0 auto;padding:6px 20px 28px;"
"color:var(--dim);font-size:12.5px;text-align:center}"
"footer a{color:var(--blue);text-decoration:none}"
"@media(max-width:620px){.row{grid-template-columns:1fr;gap:3px 0}"
".grid2{grid-template-columns:1fr}}"
"</style></head><body>"

/* OpenGlow-branded header: recreated starburst wordmark + app name */
"<header><div class='hrow'>"
"<svg width='148' height='36' viewBox='0 0 148 36' aria-label='OpenGlow'>"
"<g stroke='#e8262a' stroke-linecap='round'>"
"<line x1='34' y1='8' x2='146' y2='8' stroke-width='1.2'/>"
"<line x1='34' y1='0.5' x2='34' y2='15.5' stroke-width='1.2'/>"
"<line x1='26.5' y1='8' x2='41.5' y2='8' stroke-width='1.2'/>"
"<line x1='28.7' y1='2.7' x2='39.3' y2='13.3' stroke-width='1.1'/>"
"<line x1='39.3' y1='2.7' x2='28.7' y2='13.3' stroke-width='1.1'/>"
"<line x1='31.1' y1='1.1' x2='36.9' y2='14.9' stroke-width='.8'/>"
"<line x1='36.9' y1='1.1' x2='31.1' y2='14.9' stroke-width='.8'/>"
"<line x1='27.1' y1='5.1' x2='40.9' y2='10.9' stroke-width='.8'/>"
"<line x1='40.9' y1='5.1' x2='27.1' y2='10.9' stroke-width='.8'/>"
"</g>"
"<circle cx='34' cy='8' r='2' fill='#e8262a'/>"
"<text x='0' y='31' font-size='20' font-family='inherit'>"
"<tspan fill='#fff' font-weight='600'>Open</tspan>"
"<tspan fill='#b9bac9' font-weight='300'>Glow</tspan></text>"
"</svg>"
"<span class='appname'>ForgeFIRM</span>"
"<span id='host'></span>"
"</div></header>"
"<nav><div class='nrow'>"
"<a href='#status' id='t-status'>Status</a>"
"<a href='#machine' id='t-machine'>Machine</a>"
"<a href='#gfcloud' id='t-gfcloud'>GF Cloud</a>"
"<a href='#grbl' id='t-grbl'>GRBL</a>"
"<a href='#diag' id='t-diag'>Diagnostics</a>"
"<a href='#system' id='t-system'>System</a>"
"</div></nav><main>"
"<div id='locknote'></div>"

/* ------------------------------------------------------ status tab */
"<section id='s-status'>"
"<div class='card'><h2>Controller mode</h2>"
"<div class='seg'>"
"<button class='segbtn segon' id='mode-grbl' "
"onclick='setMode(\"grbl\")'>GRBL</button>"
"<button class='segbtn' id='mode-cloud' "
"onclick='setMode(\"cloud\")'>Factory cloud</button>"
"<span class='msg' id='msg-mode'></span>"
"</div>"
"<p class='hint'>GRBL serves standard Grbl senders on port 23. "
"Factory cloud runs the machine against the "
"Glowforge web service like stock firmware. The two are "
"mutually exclusive; a mode change takes effect on the next "
"reboot.</p></div>"
"<div class='card'><h2>Motion</h2><div id='motion'></div></div>"
"<div class='card camwrap'><h2>Lid camera</h2>"
"<img id='cam' alt='lid camera'>"
"<div class='camctl'>"
"<button id='live' data-nolock='1' onclick='toggleLive()'>Live</button>"
"<button id='snapbtn' data-nolock='1' onclick='refreshSnap()'>Refresh"
"</button>"
"</div>"
"<p class='hint' id='cammsg'></p>"
"</div>"
"<div class='grid2'>"
"<div class='card'><h2>Cooling</h2><div id='cooling'></div></div>"
"<div class='card'><h2>Switches</h2><div id='switches'></div>"
"<p class='hint'>The e-stop sense reads low whenever the machine is "
"moving &mdash; the beam is gated by the hardware safety chain "
"regardless.</p></div>"
"</div>"
"<div class='card'><h2>System</h2><div id='statgrid'></div></div>"
"</section>"

/* ----------------------------------------------------- machine tab */
"<section id='s-machine'>"
"<div class='card'><h2>Units</h2>"
"<div class='row'><label for='ui_units'>Display units</label>"
"<select id='ui_units' onchange='saveUnits()'>"
"<option value='metric'>Metric (mm, &deg;C)</option>"
"<option value='imperial'>Imperial (in, &deg;F)</option>"
"</select></div>"
"<p class='hint'>Display only &mdash; values are stored and exchanged "
"in metric. <span class='msg' id='msg-u'></span></p>"
"</div>"
"<div class='card'><h2>Homing</h2>"
"<div class='row'><label for='homing_mode'>Method</label>"
"<select id='homing_mode'>"
"<option value='none'>Disabled</option>"
"<option value='gfcloud'>Glowforge web service (cameras)</option>"
"<option value='switches'>Limit switches</option>"
"</select></div>"
"<div class='row'><label for='gfcloud_home_x'>Home position X"
"<span class='u ulen'>mm</span></label>"
"<input id='gfcloud_home_x' inputmode='decimal' placeholder='0 (origin)'>"
"</div>"
"<div class='row'><label for='gfcloud_home_y'>Home position Y"
"<span class='u ulen'>mm</span></label>"
"<input id='gfcloud_home_y' inputmode='decimal' placeholder='0 (origin)'>"
"</div>"
"<div class='row'><label for='gfcloud_home_z'>Home position Z"
"<span class='u ulen'>mm</span></label>"
"<input id='gfcloud_home_z' inputmode='decimal' "
"placeholder='top of travel'></div>"
"<p class='hint'>Machine coordinates the head is at after a completed "
"homing cycle. For Glowforge web-service homing that is the factory "
"home corner (back left) with the lens at the hall reference &mdash; "
"leave blank until a measurement says otherwise. To calibrate: home, "
"jog to a known reference, and enter the measured offsets.</p>"
"<div class='btns'><button class='pri' onclick='saveMachine()'>Save"
"</button><span class='msg' id='msg-m'></span></div>"
"</div>"
"<div class='card'><h2>Cooling</h2>"
"<div class='grid2'>"
"<div class='row'><label for='cool_flow_rise'>Flow fault rise"
"<span class='u utemp'>&deg;C</span></label>"
"<input id='cool_flow_rise' inputmode='decimal' placeholder='14.4'></div>"
"<div class='row'><label for='cool_flow_heater_pct'>Check heater duty"
"<span class='u'>%</span></label>"
"<input id='cool_flow_heater_pct' inputmode='numeric' placeholder='40'>"
"</div>"
"<div class='row'><label for='cool_flow_check_s'>Check window"
"<span class='u'>s</span></label>"
"<input id='cool_flow_check_s' inputmode='numeric' placeholder='50'></div>"
"<div class='row'><label for='cool_recheck_s'>Re-check every"
"<span class='u'>s</span></label>"
"<input id='cool_recheck_s' inputmode='numeric' placeholder='150'></div>"
"<div class='row'><label for='cool_confirm_max_s'>Suspicion budget"
"<span class='u'>s</span></label>"
"<input id='cool_confirm_max_s' inputmode='numeric' placeholder='480'>"
"</div>"
"<div class='row'><label for='cool_temp_max'>Coolant ceiling"
"<span class='u utemp'>&deg;C</span></label>"
"<input id='cool_temp_max' inputmode='decimal' placeholder='33'></div>"
"<div class='row'><label for='cool_temp_resume'>Resume below"
"<span class='u utemp'>&deg;C</span></label>"
"<input id='cool_temp_resume' inputmode='decimal' placeholder='31'></div>"
"<div class='row'><label for='cool_cooldown_s'>Smoke clear"
"<span class='u'>s</span></label>"
"<input id='cool_cooldown_s' inputmode='numeric' placeholder='15'></div>"
"<div class='row'><label for='cool_cooldown_max_s'>Cooldown limit"
"<span class='u'>s</span></label>"
"<input id='cool_cooldown_max_s' inputmode='numeric' placeholder='300'>"
"</div>"
"</div>"
"<p class='hint'>Coolant-loop protection: each running job "
"periodically verifies flow by running the loop heater and reading "
"how far the downstream sensor climbs &mdash; past the fault rise "
"means stagnant coolant. Blank fields use the built-in values "
"(placeholders), measured on this machine's factory coolant; changes "
"apply from the next job. These bands are per-machine: after a pump "
"or coolant change, run <a href='#diag'>Diagnostics &rarr; Cooling "
"system</a> to verify or re-measure them.</p>"
"<div class='btns'><button class='pri' onclick='saveCooling()'>Save"
"</button><span class='msg' id='msg-c'></span></div>"
"</div>"
"</section>"

/* ---------------------------------------------------- gfcloud tab */
"<section id='s-gfcloud'>"
"<div class='card'><h2>Machine identity</h2>"
"<div class='row'><label for='gf_serial'>Serial number</label>"
"<input id='gf_serial' inputmode='numeric' placeholder='(factory fuses)'>"
"</div>"
"<div class='row'><label for='gf_password'>Password</label>"
"<input id='gf_password' type='password' autocomplete='off'></div>"
"<p class='hint'>Credentials the machine signs in to the Glowforge "
"web service with. Blank fields use the identity burned into the "
"factory fuses &mdash; override only to stand in for another machine "
"(64 hex digit password; the service hostname derives from the "
"serial). Keep credentials secret; they cannot be changed once "
"leaked. A blank password field keeps the current override.</p>"
"<div class='btns'>"
"<button class='pri' onclick='saveIdentity()'>Save</button>"
"<button onclick='clearIdentity()'>Use factory identity</button>"
"<button data-nolock='1' onclick='showFuse()'>View fuse identity"
"</button>"
"<span class='msg' id='msg-i'></span></div>"
"</div>"
"<div class='card'><h2>Homing session</h2>"
"<div class='row'><label for='gfcloud_home_timeout_s'>Session timeout"
"<span class='u'>seconds</span></label>"
"<input id='gfcloud_home_timeout_s' inputmode='numeric' "
"placeholder='300'></div>"
"<p class='hint'>Overall budget for one web-service homing run "
"(sign-in, camera uploads, hunt and corner moves). The controller "
"aborts and alarms past this; 30&ndash;3600.</p>"
"<div class='btns'><button class='pri' onclick='saveSession()'>Save"
"</button><span class='msg' id='msg-s'></span></div>"
"</div>"
"</section>"

/* ------------------------------------------------------- grbl tab */
"<section id='s-grbl'>"
"<div class='card'><h2>Controller</h2><div id='grblinfo'></div>"
"<p class='hint'>The motion controller speaks standard Grbl 1.1 "
"(grblHAL) &mdash; point your sender at the connection above and use "
"its device settings ($$) for the numbered GRBL parameters. "
"GRBL-mode tunables will appear on this tab as the controller "
"exposes them.</p>"
"</div>"
"</section>"

/* ------------------------------------------------------- diag tab */
"<section id='s-diag'>"
"<div class='card'><h2>Cooling system</h2>"
"<p class='hint' style='margin-top:0'>These tools take the machine "
"over: the motion controller is stopped, the loop heater and pump are "
"driven directly, and the controller restarts when the tool finishes. "
"The laser stays locked out throughout. Launch only when idle; all "
"other controls lock until completion.</p>"
"<div class='btns'>"
"<button class='pri' onclick='startDiag(\"flow-verify\")'>"
"Verify flow check</button>"
"<button onclick='startDiag(\"flow-calibrate\")'>"
"Calibrate thresholds</button>"
"<button id='diagabort' data-nolock='1' style='display:none' "
"onclick='abortDiag()'>Abort</button>"
"<span class='msg' id='msg-d'></span></div>"
"<p class='hint'>&bull; <b>Verify</b> (~10 min): one flow check with "
"the pump running and one with it stopped, judged against the "
"configured fault rise &mdash; proves the threshold separates the two "
"on this machine and coolant.<br>&bull; <b>Calibrate</b> (~30 min): "
"three trials per case; measures both bands and recommends a "
"threshold at the midpoint. Run it after replacing the coolant (a "
"different blend carries heat differently), swapping the pump, or a "
"failed verify.</p>"
"<div id='diagpanel'></div>"
"<div id='diaglog'></div>"
"<div id='diagresult'></div>"
"</div>"
"</section>"

/* ----------------------------------------------------- system tab */
"<section id='s-system'>"
"<div class='card'><h2>Firmware slots</h2>"
"<div id='slottbl'></div>"
"<p class='hint'>The eMMC carries two firmware slots (the factory A/B "
"scheme); the SD card is the development boot medium. <b>Set next "
"boot</b> changes only the saved boot selection &mdash; the machine "
"keeps running until you reboot. Targets are probed first and "
"unbootable ones are refused.<br><b>Switching to factory firmware:</b> "
"while factory firmware is online it may update itself and overwrite "
"the other slot. Return to ForgeFIRM with <span class='mono'>"
"sh /data/ffboot -e&lt;slot&gt;</span> at the factory console.</p>"
"<div class='btns'>"
"<button onclick='doReboot()'>Reboot now</button>"
"<span class='msg' id='msg-slot'></span></div>"
"</div>"
"<div class='card'><h2>ForgeFIRM update</h2>"
"<div id='updinfo'></div>"
"<div class='btns'>"
"<button class='pri' onclick='checkUpd()'>Check for updates</button>"
"<button id='dlbtn' style='display:none' onclick='dlUpd()'>Download"
"</button>"
"<span class='msg' id='msg-u'></span></div>"
"<p class='hint'>Downloads are verified against the ForgeFIRM release "
"signing key before anything can be written. Installing writes the "
"selected slot; the running system is untouched until you set next "
"boot and reboot.</p>"
"</div>"
"<div class='card'><h2>Install or restore firmware</h2>"
"<div class='row'><label for='applyslot'>Target slot"
"<span class='u'>overwritten</span></label>"
"<select id='applyslot' onchange='renderLists()'></select></div>"
"<p class='hint' style='margin-top:4px'>Every Install and Restore "
"button below writes <b>this</b> slot and re-verifies it. The running "
"system is never touched; the booted slot is not an option. After "
"writing, use <b>Set next boot</b> above and reboot to switch.</p>"
"<h2 style='margin-top:16px'>Install a firmware image</h2>"
"<div id='stagedlist'></div>"
"<div class='btns'>"
"<input type='file' id='fwfile' style='width:auto' accept='.fw'>"
"<button onclick='uploadFw()'>Upload .fw</button>"
"<span class='msg' id='msg-up'></span></div>"
"<p class='hint'>Development images upload straight from the browser "
"(dev-key signed &mdash; <span class='mono'>release.sh --dev</span>); "
"unsigned images need an extra confirmation.</p>"
"<h2 style='margin-top:16px'>Restore factory firmware</h2>"
"<div id='archlist'></div>"
"<p class='hint'>Restores an archived factory image (md5-verified "
"against the archive manifest first). The Glowforge cloud is never "
"required.</p>"
"<span class='msg' id='msg-r'></span>"
"</div>"
"<div class='card'><h2>Update job</h2><div id='jobpanel' "
"class='kv'>no job running</div></div>"
"<div class='card'><h2>Wireless</h2>"
"<div class='row'><label for='wifi_country'>Regulatory region</label>"
"<select id='wifi_country'></select></div>"
"<p class='hint'>Region rules set the WiFi radio's allowed channels "
"and transmit power. Automatic follows the country the access point "
"advertises (802.11d), falling back to the most-restrictive world "
"rules; selecting a country pins it regardless of the AP "
"(2.4&nbsp;GHz channels 12&ndash;13 and the 5&nbsp;GHz bands vary "
"by region). Applied immediately and at every boot. WiFi power save "
"stays off &mdash; on a mains-powered machine it only adds "
"latency.</p>"
"<div class='btns'><button class='pri' onclick='saveWifi()'>Save"
"</button><span class='msg' id='msg-w'></span></div>"
"</div>"
"</section>"
"</main>"

/* fuse-identity viewer: modal, fetched on demand, outside <main> so
 * the settings lock never touches it (viewing is read-only) */
"<div id='fusewrap'>"
"<div class='fusebox'>"
"<h2>Fuse identity</h2>"
"<div id='fusekv'></div>"
"<p class='fwarn'>Burned into the machine at the factory and "
"unchangeable. Keep these secret &mdash; a leaked identity cannot "
"be rotated, only abandoned.</p>"
"<div class='btns'><button class='pri' onclick='hideFuse()'>Close"
"</button></div>"
"</div></div>"

"<footer>ForgeFIRM is an <a href='https://community.openglow.org'>"
"OpenGlow</a> project</footer>"

/* ------------------------------------------------------------- js */
"<script>"
"var S={},CS={},M={},D={},liveOn=false,retries=0,locked=false;"
"var CK=['cool_flow_rise','cool_flow_heater_pct','cool_flow_check_s',"
"'cool_recheck_s','cool_confirm_max_s','cool_temp_max',"
"'cool_temp_resume','cool_cooldown_s','cool_cooldown_max_s'];"
"function $(i){return document.getElementById(i)}"
"function esc(t){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;')}"

/* display units: the backend stores and exchanges metric only;
 * conversion happens at the UI edge. Temperature DELTAS (the flow
 * rise family) scale by 1.8 with no 32 offset. */
"function isImp(){return (S.ui_units||'metric')==='imperial'}"
"function uL(){return isImp()?'in':'mm'}"
"function uT(){return isImp()?'\\u00b0F':'\\u00b0C'}"
"function fnum(x,dp){return String(parseFloat(x.toFixed(dp)))}"
"function dLen(v){return isImp()?v/25.4:v}"
"function dTa(v){return isImp()?v*1.8+32:v}"
"function dTd(v){return isImp()?v*1.8:v}"
"function pLen(v){return isImp()?v*25.4:v}"
"function pTa(v){return isImp()?(v-32)/1.8:v}"
"function pTd(v){return isImp()?v/1.8:v}"

/* form fields: per-field unit type, display placeholders for the
 * built-in defaults, and dirty tracking - a save posts only fields
 * whose display string changed since fill(), so unit round-trips
 * never masquerade as edits */
"var FT={gfcloud_home_x:'len',gfcloud_home_y:'len',gfcloud_home_z:'len',"
"cool_flow_rise:'td',cool_temp_max:'ta',cool_temp_resume:'ta'};"
"var PH={cool_flow_rise:[14.4,'td'],cool_temp_max:[33,'ta'],"
"cool_temp_resume:[31,'ta']};"
"var orig={};"
"function dspVal(k,raw){var f=parseFloat(raw);"
"if(raw===''||isNaN(f)||!FT[k])return raw;"
"return FT[k]==='len'?fnum(dLen(f),3):"
"fnum(FT[k]==='ta'?dTa(f):dTd(f),1)}"
"function backVal(k,s){var f=parseFloat(s);"
"if(s===''||isNaN(f)||!FT[k])return s;"
"return FT[k]==='len'?fnum(pLen(f),3):"
"fnum(FT[k]==='ta'?pTa(f):pTd(f),2)}"
"function setF(k,raw){var v=dspVal(k,raw||'');$(k).value=v;orig[k]=v}"
"function dirty(k){return $(k).value.trim()!==orig[k]}"
"function pick(p,keys){var i,k,any=0;"
"for(i=0;i<keys.length;i++){k=keys[i];if(dirty(k)){"
"p[k]=backVal(k,$(k).value.trim());any=1}}return any}"

/* settings lock: everything but the camera controls is disabled while
 * the machine is not idle or a diagnostic owns the hardware (the
 * server rejects writes then too) */
"function lockApply(){"
"var els=document.querySelectorAll('main input,main select,main button');"
"for(var i=0;i<els.length;i++){var e=els[i];"
"if(e.getAttribute('data-nolock'))continue;"
"e.disabled=locked||e.getAttribute('data-off')==='1'}"
"$('locknote').style.display=locked?'block':'none';"
"if(locked)$('locknote').textContent=D.running?"
"'A diagnostic is running \\u2014 controls are locked until it "
"completes.':"
"'Settings are locked while the machine is busy (state: '+"
"(M.state||'unknown')+').'}"
"function setMode(m){post({controller_mode:m},'msg-mode')}"

/* hash-routed tabs */
"var TABS=['status','machine','gfcloud','grbl','diag','system'],"
"sysChecked=false;"
"function tab(){var h=location.hash.replace('#','');"
"if(TABS.indexOf(h)<0)h='status';"
"for(var i=0;i<TABS.length;i++){var t=TABS[i];"
"$('s-'+t).className=t===h?'on':'';"
"$('t-'+t).className=t===h?'on':''}"
/* auto-check for a ForgeFIRM update the first time the System tab is
 * opened - once per page load, so the GitHub endpoint is not hit on a
 * timer from every machine */
"if(h==='system'&&!sysChecked){sysChecked=true;checkUpd()}}"
"window.onhashchange=tab;"

/* camera: scaled snapshot by default, live stream on demand */
"function snapUrl(){return '/cam/snapshot?cam=lid&res=half&t='+Date.now()}"
"function refreshSnap(){if(!liveOn)$('cam').src=snapUrl()}"
"function toggleLive(){liveOn=!liveOn;retries=0;$('cammsg').textContent='';"
"$('live').textContent=liveOn?'Stop':'Live';"
"$('live').className=liveOn?'on':'';"
"$('snapbtn').disabled=liveOn;"
"$('cam').src=liveOn?'/cam/stream?cam=lid&t='+Date.now():snapUrl()}"
"$('cam').onerror=function(){if(!liveOn)return;"
"fetch('/cam/status').then(function(r){return r.json()})"
".then(function(s){if(s.cam==='lid'&&retries++<5){"
"$('cammsg').textContent='stream retrying\\u2026';"
"setTimeout(function(){if(liveOn)$('cam').src='/cam/stream?cam=lid&t='+"
"Date.now()},700)}else{$('cammsg').textContent=s.cam!=='lid'?"
"'stream taken by another viewer ('+s.cam+')':'stream error';"
"toggleLive()}}).catch(function(){"
"$('cammsg').textContent='service unreachable'})};"

/* rendering helpers */
"function kv(k,v,cls){return \"<div class='kv'><span>\"+esc(k)+"
"\"</span><span\"+(cls?\" class='\"+cls+\"'\":'')+'>'+v+'</span></div>'}"
"function txt(k,v,cls){return kv(k,esc(v),cls)}"
"function modeName(m){return m==='gfcloud'?'Glowforge web service':"
"m==='switches'?'Limit switches':'Disabled'}"

/* operational status (/status, 2.5 s poll) */
"function stateBadge(st){var c=st==='idle'?'b-ok':st==='running'?"
"'b-run':st==='disabled'?'b-dim':'b-bad';"
"return txt('State',st,c)}"
/* position shows even unreferenced (relative to start) - painted red
 * until a homing cycle anchors it */
"function posN(v){return dLen(v).toFixed(isImp()?3:2)}"
"function renderMotion(){var g='';"
"g+=stateBadge(M.state||'unknown');"
"if(M.pos)g+=kv('Position',\"<span class='mono\"+"
"(M.homed?'':' b-bad')+\"'>X \"+posN(M.pos.x)+' &nbsp;Y '+"
"posN(M.pos.y)+' &nbsp;Z '+posN(M.pos.z)+' '+uL()+'</span>');"
"g+=txt('Homed',M.homed?'yes':'no',M.homed?'b-ok':'b-dim');"
"if(typeof M.laser_locked!=='undefined')"
"g+=txt('Laser lockout',M.laser_locked?'locked':'UNLOCKED',"
"M.laser_locked?'b-ok':'b-bad');"
"$('motion').innerHTML=g}"
"function rpm(v){return v>0?v+' rpm':'stopped'}"
"function degc(v){return v>-100?dTa(v).toFixed(1)+' '+uT():'\\u2014'}"
"function renderCooling(){if(!M.coolant)return;var g='';"
"g+=txt('Coolant out',degc(M.coolant.down_c));"
"g+=txt('Coolant in',degc(M.coolant.up_c));"
"g+=txt('Pump',M.coolant.pump?'on':'off',M.coolant.pump?'b-ok':'b-warn');"
"g+=txt('TEC',M.coolant.tec?'on':'off','b-dim');"
"if(M.fans){g+=txt('Air assist',rpm(M.fans.air_assist));"
"g+=txt('Exhaust',rpm(M.fans.exhaust));"
"g+=txt('Intake 1',rpm(M.fans.intake_1));"
"g+=txt('Intake 2',rpm(M.fans.intake_2))}"
"$('cooling').innerHTML=g}"
"function sw(k,name,on,off,onCls,offCls){var v=M.switches[k];"
"return txt(name,v?on:off,v?onCls:offCls)}"
"function renderSwitches(){if(!M.switches)return;var g='';"
"g+=sw('lid','Lid','closed','OPEN','b-ok','b-warn');"
"g+=sw('button','Button','pressed','released','b-run','b-dim');"
"g+=sw('interlock_ok','Remote interlock','satisfied','OPEN (lockout)',"
"'b-ok','b-warn');"
"g+=sw('head','Head sense','detected','not detected','b-ok','b-dim');"
"g+=sw('estop','E-stop sense','ok','low','b-ok','b-dim');"
"$('switches').innerHTML=g}"
"function renderStat(){var g='';"
"g+=txt('Firmware',S.version||'\\u2014');"
"g+=txt('Homing',modeName(S.homing_mode));"
"g+=txt('Identity',S.gf_serial?'Override (S'+S.gf_serial+')':"
"'Factory fuses');"
"g+=kv('Controller',\"<span class='mono'>\"+esc(location.hostname)+"
"':23</span> (Grbl 1.1)');"
"if(CS.running)g+=txt('Camera engine',CS.cam+' camera, '+"
"(CS.fps||0).toFixed(1)+' fps, '+CS.encoder+', '+CS.clients+"
"' viewer'+(CS.clients===1?'':'s'));"
"else g+=txt('Camera engine','idle');"
"$('statgrid').innerHTML=g}"
"function renderGrbl(){var g='';"
"g+=txt('Protocol','Grbl 1.1 (grblHAL)');"
"g+=kv('Connection',\"<span class='mono'>\"+esc(location.hostname)+"
"':23</span>');"
"g+=kv('Camera stream',\"<span class='mono'>http://\"+"
"esc(location.host)+'/?action=stream</span>');"
"$('grblinfo').innerHTML=g}"

/* settings load/save */
"function fill(){"
"$('mode-grbl').className='segbtn'+"
"((S.controller_mode||'grbl')==='grbl'?' segon':'');"
"$('mode-cloud').className='segbtn'+"
"(S.controller_mode==='cloud'?' segon':'');"
"$('ui_units').value=S.ui_units||'metric';"
"setF('homing_mode',S.homing_mode||'none');"
"setF('gfcloud_home_x',S.gfcloud_home_x);"
"setF('gfcloud_home_y',S.gfcloud_home_y);"
"setF('gfcloud_home_z',S.gfcloud_home_z);"
"setF('gfcloud_home_timeout_s',S.gfcloud_home_timeout_s);"
"for(var ci=0;ci<CK.length;ci++)setF(CK[ci],S[CK[ci]]);"
"setF('wifi_country',S.wifi_country||'00');"
"setF('gf_serial',S.gf_serial);"
"$('gf_password').value='';"
"$('gf_password').placeholder=S.gf_password_set?"
"'(override set \\u2014 blank keeps it)':'(factory fuses)';"
"var uu=document.querySelectorAll('.ulen'),ui;"
"for(ui=0;ui<uu.length;ui++)uu[ui].textContent=uL();"
"uu=document.querySelectorAll('.utemp');"
"for(ui=0;ui<uu.length;ui++)uu[ui].textContent=uT();"
"for(var pk in PH)$(pk).placeholder="
"fnum(PH[pk][1]==='ta'?dTa(PH[pk][0]):dTd(PH[pk][0]),1);"
"$('host').textContent=(S.machine_id||'')+"
"(S.version?' \\u00b7 '+S.version:'');"
"renderStat()}"
/* settings go in the query string: empty values (= clear the key)
 * are dropped from form bodies by the HTTP stack */
"function post(pairs,msgId){var q='',k;"
"for(k in pairs)q+=(q?'&':'')+encodeURIComponent(k)+'='+"
"encodeURIComponent(pairs[k]);"
"$(msgId).textContent='saving\\u2026';"
"fetch('/settings?'+q,{method:'POST'})"
".then(function(r){if(!r.ok)return r.text().then(function(t)"
"{throw t});return r.json()})"
".then(function(s){S=s;fill();$(msgId).textContent='saved';"
"setTimeout(function(){$(msgId).textContent=''},2500)})"
".catch(function(e){$(msgId).textContent=String(e||'save failed')})}"
"function saveUnits(){post({ui_units:$('ui_units').value},'msg-u')}"
"function saveMachine(){var p={};"
"if(!pick(p,['homing_mode','gfcloud_home_x','gfcloud_home_y',"
"'gfcloud_home_z'])){$('msg-m').textContent='no changes';return}"
"post(p,'msg-m')}"
"function saveCooling(){var p={};"
"if(!pick(p,CK)){$('msg-c').textContent='no changes';return}"
"post(p,'msg-c')}"
"function saveIdentity(){var p={};pick(p,['gf_serial']);"
"if($('gf_password').value)p.gf_password=$('gf_password').value.trim();"
"if(!Object.keys(p).length){$('msg-i').textContent='no changes';return}"
"post(p,'msg-i')}"
"function clearIdentity(){post({gf_serial:'',gf_password:''},'msg-i')}"
"function saveSession(){var p={};"
"if(!pick(p,['gfcloud_home_timeout_s'])){"
"$('msg-s').textContent='no changes';return}"
"post(p,'msg-s')}"

/* wireless regulatory region: ISO 3166-1 alpha-2 codes with
 * ASCII-folded English names, sorted by name; 00 is the kernel's
 * built-in world domain (the default when the key is unset) */
"var RG=\"AF Afghanistan;AX Aland Islands;AL Albania;DZ Algeria;AS American"
" Samoa;AD Andorra;AO Angola;AI Anguilla;AG Antigua & Barbuda;AR Argentina;"
"AM Armenia;AW Aruba;AU Australia;AT Austria;AZ Azerbaijan;BS Bahamas;BH Ba"
"hrain;BD Bangladesh;BB Barbados;BY Belarus;BE Belgium;BZ Belize;BJ Benin;B"
"M Bermuda;BT Bhutan;BO Bolivia;BQ Bonaire, Sint Eustatius and Saba;BA Bosn"
"ia and Herzegovina;BW Botswana;BR Brazil;IO British Indian Ocean Territory"
";VG British Virgin Islands;BN Brunei;BG Bulgaria;BF Burkina Faso;BI Burund"
"i;CV Cabo Verde;KH Cambodia;CM Cameroon;CA Canada;KY Cayman Islands;CF Cen"
"tral African Republic;TD Chad;CL Chile;CN China;CX Christmas Island;CC Coc"
"os (Keeling) Islands;CO Colombia;KM Comoros;CG Congo;CD Congo (DRC);CK Coo"
"k Islands;CR Costa Rica;CI Cote d'Ivoire;HR Croatia;CU Cuba;CW Curacao;CY "
"Cyprus;CZ Czechia;DK Denmark;DJ Djibouti;DM Dominica;DO Dominican Republic"
";EC Ecuador;EG Egypt;SV El Salvador;GQ Equatorial Guinea;ER Eritrea;EE Est"
"onia;SZ Eswatini;ET Ethiopia;FK Falkland Islands;FO Faroe Islands;FJ Fiji;"
"FI Finland;FR France;GF French Guiana;PF French Polynesia;GA Gabon;GM Gamb"
"ia;GE Georgia;DE Germany;GH Ghana;GI Gibraltar;GR Greece;GL Greenland;GD G"
"renada;GP Guadeloupe;GU Guam;GT Guatemala;GG Guernsey;GN Guinea;GW Guinea-"
"Bissau;GY Guyana;HT Haiti;HN Honduras;HK Hong Kong SAR;HU Hungary;IS Icela"
"nd;IN India;ID Indonesia;IR Iran;IQ Iraq;IE Ireland;IM Isle of Man;IL Isra"
"el;IT Italy;JM Jamaica;JP Japan;JE Jersey;JO Jordan;KZ Kazakhstan;KE Kenya"
";KI Kiribati;KR Korea;XK Kosovo;KW Kuwait;KG Kyrgyzstan;LA Laos;LV Latvia;"
"LB Lebanon;LS Lesotho;LR Liberia;LY Libya;LI Liechtenstein;LT Lithuania;LU"
" Luxembourg;MO Macao SAR;MG Madagascar;MW Malawi;MY Malaysia;MV Maldives;M"
"L Mali;MT Malta;MH Marshall Islands;MQ Martinique;MR Mauritania;MU Mauriti"
"us;YT Mayotte;MX Mexico;FM Micronesia;MD Moldova;MC Monaco;MN Mongolia;ME "
"Montenegro;MS Montserrat;MA Morocco;MZ Mozambique;MM Myanmar;NA Namibia;NR"
" Nauru;NP Nepal;NL Netherlands;NC New Caledonia;NZ New Zealand;NI Nicaragu"
"a;NE Niger;NG Nigeria;NU Niue;NF Norfolk Island;KP North Korea;MK North Ma"
"cedonia;MP Northern Mariana Islands;NO Norway;OM Oman;PK Pakistan;PW Palau"
";PS Palestinian Authority;PA Panama;PG Papua New Guinea;PY Paraguay;PE Per"
"u;PH Philippines;PN Pitcairn Islands;PL Poland;PT Portugal;PR Puerto Rico;"
"QA Qatar;RE Reunion;RO Romania;RU Russia;RW Rwanda;WS Samoa;SM San Marino;"
"ST Sao Tome & Principe;SA Saudi Arabia;SN Senegal;RS Serbia;SC Seychelles;"
"SL Sierra Leone;SG Singapore;SX Sint Maarten;SK Slovakia;SI Slovenia;SB So"
"lomon Islands;SO Somalia;ZA South Africa;SS South Sudan;ES Spain;LK Sri La"
"nka;SH St Helena, Ascension, Tristan da Cunha;BL St. Barthelemy;KN St. Kit"
"ts & Nevis;LC St. Lucia;MF St. Martin;PM St. Pierre & Miquelon;VC St. Vinc"
"ent & Grenadines;SD Sudan;SR Suriname;SJ Svalbard & Jan Mayen;SE Sweden;CH"
" Switzerland;SY Syria;TW Taiwan;TJ Tajikistan;TZ Tanzania;TH Thailand;TL T"
"imor-Leste;TG Togo;TK Tokelau;TO Tonga;TT Trinidad & Tobago;TN Tunisia;TR "
"Turkiye;TM Turkmenistan;TC Turks & Caicos Islands;TV Tuvalu;UM U.S. Outlyi"
"ng Islands;VI U.S. Virgin Islands;UG Uganda;UA Ukraine;AE United Arab Emir"
"ates;GB United Kingdom;US United States;UY Uruguay;UZ Uzbekistan;VU Vanuat"
"u;VA Vatican City;VE Venezuela;VN Vietnam;WF Wallis & Futuna;YE Yemen;ZM Z"
"ambia;ZW Zimbabwe\";"
"(function(){var s=$('wifi_country'),a=RG.split(';'),i;"
"s.add(new Option('Automatic \\u2014 AP country, else World (00)','00'));"
"for(i=0;i<a.length;i++)s.add(new Option(a[i].slice(3)+' ('+"
"a[i].slice(0,2)+')',a[i].slice(0,2)))})();"
"function saveWifi(){var p={};if(!pick(p,['wifi_country'])){"
"$('msg-w').textContent='no changes';return}"
"post(p,'msg-w')}"

/* fuse-identity viewer (backdrop click or Close dismisses) */
"function showFuse(){fetch('/fuse-identity')"
".then(function(r){return r.json()}).then(function(f){var g='';"
"g+=kv('Serial',\"<span class='mono'>\"+esc(f.serial||'?')+'</span>');"
"g+=kv('Hostname',\"<span class='mono'>\"+esc(f.hostname||'?')+"
"'</span>');"
"g+=kv('Password',\"<span class='mono brk'>\"+esc(f.password||'?')+"
"'</span>');"
"$('fusekv').innerHTML=g;$('fusewrap').className='on'})"
".catch(function(){$('msg-i').textContent='cannot read fuses'})}"
"function hideFuse(){$('fusewrap').className='';"
"$('fusekv').innerHTML=''}"
"$('fusewrap').onclick=function(e){"
"if(e.target===this)hideFuse()};"

/* diagnostics endpoints, 2.5 s poll */
"function startDiag(t){$('msg-d').textContent='starting\\u2026';"
"fetch('/diag/'+t,{method:'POST'})"
".then(function(r){if(!r.ok)return r.text().then(function(x){throw x});"
"$('msg-d').textContent='';loadDiag()})"
".catch(function(e){$('msg-d').textContent=String(e||'failed')})}"
"function abortDiag(){fetch('/diag/abort',{method:'POST'})}"
"function applyRec(v){post({cool_flow_rise:String(v)},'msg-d')}"
"function fmtEl(s){return Math.floor(s/60)+':'+('0'+s%60).slice(-2)}"
"function renderDiag(){var p='',r=D.result,g='';"
"if(D.running){$('diagabort').style.display='';"
"p+=kv('Phase',esc(D.phase||''));"
"p+=kv('Elapsed',fmtEl(D.elapsed_s||0));"
"p+=kv('Coolant',\"<span class='mono'>down \"+dTa(D.down_c||0)"
".toFixed(1)+' / up '+dTa(D.up_c||0).toFixed(1)+' '+uT()+'</span>')}"
"else $('diagabort').style.display='none';"
"$('diagpanel').innerHTML=p;"
"var lg=$('diaglog');"
"if(D.log&&D.log.length){lg.style.display='block';"
"lg.textContent=D.log.join('\\n');lg.scrollTop=lg.scrollHeight}"
"else lg.style.display='none';"
"if(r&&!D.running){"
"if(typeof r.pass!=='undefined'){"
"g+=txt('Result',r.pass?'PASS':'FAIL',r.pass?'bigpass':'bigfail');"
"g+=txt('Flow rise',dTd(r.flow_rise).toFixed(1)+' '+uT()+' (dT '+"
"dTd(r.flow_dt).toFixed(1)+')');"
"g+=txt('No-flow rise',dTd(r.noflow_rise).toFixed(1)+' '+uT()+' (dT '+"
"dTd(r.noflow_dt).toFixed(1)+')');"
"g+=txt('Threshold',dTd(r.threshold).toFixed(1)+' '+uT());"
"g+=txt('Margins','flow '+dTd(r.margin_flow).toFixed(1)+"
"' / no-flow '+dTd(r.margin_noflow).toFixed(1)+' '+uT(),"
"r.thin_margin?'b-warn':'b-ok');"
"if(r.thin_margin)g+=txt('Note','margin under '+fnum(dTd(1.5),1)+' '+"
"uT()+' \\u2014 run Calibrate','b-warn');"
"if(!r.pass&&!r.error)g+=txt('Note',"
"'check pump and coolant, or run Calibrate','b-warn')}"
"if(typeof r.gap!=='undefined'){"
"var f1=function(x){return dTd(x).toFixed(1)};"
"g+=txt('Flow band','\\u2264 '+f1(r.flow_max)+' '+uT()+'  ('+"
"r.flow_rises.map(f1).join(', ')+')');"
"g+=txt('No-flow band','\\u2265 '+f1(r.noflow_min)+' '+uT()+'  ('+"
"r.noflow_rises.map(f1).join(', ')+')');"
"g+=txt('Gap',f1(r.gap)+' '+uT(),r.recommend?'b-ok':'b-warn');"
"if(r.recommend)g+=kv('Recommended threshold',"
"\"<span class='mono'>\"+f1(r.recommend)+' '+uT()+'</span> '+"
"\"<button class='pri' onclick='applyRec(\"+r.recommend+"
"\")'>Apply</button>\")}"
"if(r.error)g+=txt('Result',r.error,'bigfail')}"
"$('diagresult').innerHTML=g}"
"function loadDiag(){fetch('/diag/status').then(function(r)"
"{return r.json()}).then(function(d){var was=!!D.running;D=d;"
"renderDiag();if(was!==!!D.running){locked=locked||D.running;"
"lockApply()}}).catch(function(){})}"

/* system tab: slots, updates, restore. Buttons carry data attributes
 * and one delegated handler dispatches - no argument quoting inside
 * generated HTML. */
"var SL={},jobTimer=null,lastApply=null;"
"var SLNAME={sd:'SD card',a:'eMMC slot 1',b:'eMMC slot 2',"
"legacy:'Legacy partition'};"
"function slotRow(n,s){var b='';"
"if(s.booted)b+=\" <span class='b-ok'>booted</span>\";"
"if(s.next)b+=\" <span class='b-run'>next boot</span>\";"
"var lbl=s.present==='yes'?(s.type?esc(s.type)+' '+esc(s.version):"
"'(empty)'):'(not present)';"
"var act=(s.present==='yes'&&!s.next)?"
"\" <button data-boot='\"+n+\"'>Set next boot</button>\":'';"
"return \"<div class='kv'><span>\"+SLNAME[n]+\"</span><span>\"+lbl+b+"
"act+\"</span></div>\"}"
/* current target-slot descriptor (name + what it holds now) */
"function tgt(){var n=$('applyslot').value;if(!n)return null;"
"var s=(SL.slots||{})[n]||{};return {slot:n,name:SLNAME[n]||n,"
"cur:s.type?esc(s.type)+' '+esc(s.version||''):'empty'}}"
/* friendly archive label: semantic version, else build date, else file */
"function archName(a){return a.version?'Factory v'+esc(a.version):"
"(a.date?'Factory build '+esc(a.date):esc(a.file))}"
"function renderSlots(){var g='',n,sl=SL.slots||{};"
"for(n in sl)g+=slotRow(n,sl[n]);"
"$('slottbl').innerHTML=g;"
/* target options: writable (present, not booted) a/b, non-factory
 * first so the default never lands on factory firmware */
"var prev=$('applyslot').value,opts=[],t=['a','b'],i;"
"for(i=0;i<t.length;i++){var s=sl[t[i]]||{};"
"if(s.booted||s.present!=='yes')continue;"
"opts.push({v:t[i],f:s.type==='factory',"
"label:SLNAME[t[i]]+' \\u2014 '+esc(s.type||'empty')+' '+"
"esc(s.version||'')})}"
"opts.sort(function(x,y){return (x.f?1:0)-(y.f?1:0)});"
"var sel='';for(i=0;i<opts.length;i++)sel+=\"<option value='\"+"
"opts[i].v+\"'>\"+opts[i].label+'</option>';"
"$('applyslot').innerHTML=sel||\"<option value=''>(none writable)"
"</option>\";if(prev)$('applyslot').value=prev;"
"renderLists()}"
"function renderLists(){var tg=tgt(),to=tg?tg.name:'the target slot',"
"n,i;"
"var st=SL.staged||{},g2='';"
"var lb={download:'Downloaded release',upload:'Uploaded archive'};"
"for(n in lb){var e=st[n]||{};if(!e.present)continue;"
"g2+=\"<div class='kv'><span>\"+lb[n]+\"</span><span class='mono'>\"+"
"esc(e.version||'?')+' \\u00b7 '+Math.round(e.bytes/1048576)+' MB'+"
"\" <button class='pri' data-apply='\"+n+\"' data-ver='\"+"
"esc(e.version||'this image')+\"'>Install to \"+esc(to)+"
"\"</button></span></div>\"}"
"$('stagedlist').innerHTML=g2||\"<p class='hint'>Nothing staged yet."
"</p>\";"
"var ar=SL.archives||[],g3='';"
"for(i=0;i<ar.length;i++){var a=ar[i];"
"g3+=\"<div class='kv'><span>\"+archName(a)+\"</span>"
"<span class='mono'>\"+Math.round(a.bytes/1048576)+' MB'+"
"\" <button data-restore='\"+a.file+\"' data-ver='\"+"
"esc(a.version?'v'+a.version:(a.date||a.file))+\"'>Restore to \"+"
"esc(to)+\"</button></span></div>\"}"
"$('archlist').innerHTML=g3||\"<p class='hint'>No factory archives on "
"/data (the installer creates them).</p>\"}"
"function loadSlots(){fetch('/slots').then(function(r){return r.json()})"
".then(function(s){SL=s;renderSlots()}).catch(function(){})}"
"function bootTo(t,f){fetch('/boot?target='+t+(f?'&force=1':''),"
"{method:'POST'}).then(function(r){return r.json()})"
".then(function(j){if(j.ok){$('msg-slot').textContent="
"'next boot set \\u2014 reboot to switch';loadSlots()}"
"else if(!f&&j.detail&&j.detail.indexOf('-f')>=0&&"
"confirm('The probe refused this target:\\n'+j.detail+"
"'\\nForce anyway?'))bootTo(t,1);"
"else $('msg-slot').textContent=(j.error||'?')+"
"(j.detail?': '+j.detail:'')})}"
"function doReboot(){if(!confirm('Reboot the machine now?'))return;"
"fetch('/system/reboot?confirm=1',{method:'POST'})"
".then(function(r){return r.json()}).then(function(j){"
"$('msg-slot').textContent=j.rebooting?'rebooting\\u2026':"
"(j.error||'?')})}"
"function checkUpd(){$('msg-u').textContent='checking\\u2026';"
"fetch('/update/check',{method:'POST'})"
".then(function(r){return r.json()}).then(function(j){"
"if(j.error){$('msg-u').textContent=j.error;return}"
"$('msg-u').textContent='';"
"var g=\"<div class='kv'><span>Installed</span><span class='mono'>\"+"
"esc(j.current||'?')+'</span></div>';"
"if(j.available)g+=\"<div class='kv'><span>Latest release</span>"
"<span class='mono'>\"+esc(j.version)+(j['new']?"
"\" <span class='b-run'>update available</span>\":"
"\" <span class='b-ok'>up to date</span>\")+'</span></div>';"
"else g+=\"<div class='kv'><span>Latest release</span><span>\"+"
"esc(j.detail||'none')+'</span></div>';"
"$('updinfo').innerHTML=g;"
"$('dlbtn').style.display=(j.available&&j['new'])?'':'none'})"
".catch(function(){$('msg-u').textContent='check failed'})}"
"function jobPoll(){fetch('/update/status')"
".then(function(r){return r.json()}).then(function(j){var g;"
"if(j.running){g=esc(j.kind)+': '+esc(j.phase||'\\u2026')+' ('+"
"j.elapsed+'s'+(j.progress_bytes>0?', '+"
"Math.round(j.progress_bytes/1048576)+' MB':'')+')';"
"if(!jobTimer)jobTimer=setInterval(jobPoll,2000)}"
"else{if(jobTimer){clearInterval(jobTimer);jobTimer=null;loadSlots()}"
"if(j.result&&j.result.ok===false&&"
"String(j.result.error||'').indexOf('confirm_unsigned')>=0&&"
"lastApply&&confirm('The archive is not signed with the release "
"key.\\nInstall it anyway?')){"
"startJob('/update/apply','file='+lastApply.f+'&slot='+lastApply.s+"
"'&confirm_unsigned=1','msg-up');lastApply=null;return}"
"g=j.result?(j.result.ok?\"<span class='b-ok'>\"+esc(j.kind)+"
"' ok'+(j.result.version?' \\u2014 '+esc(j.result.version):'')+"
"'</span>':\"<span class='b-bad'>\"+esc(j.result.error||'failed')+"
"'</span>'):'no job running'}"
"$('jobpanel').innerHTML=g}).catch(function(){})}"
"function startJob(url,q,msgid){$(msgid).textContent='';"
"fetch(url+(q?'?'+q:''),{method:'POST'})"
".then(function(r){return r.json()}).then(function(j){"
"if(j.started)jobPoll();else $(msgid).textContent=j.error||'?'})}"
"function dlUpd(){startJob('/update/download','','msg-u')}"
"function applyStaged(f,ver){var t=tgt();"
"if(!t){$('msg-up').textContent='no writable target slot';return}"
"if(!confirm('Install '+ver+' to '+t.name+'?\\nThis ERASES its current "
"contents ('+t.cur+').'))return;"
"lastApply={f:f,s:t.slot};"
"startJob('/update/apply','file='+f+'&slot='+t.slot,'msg-up')}"
"function restoreArch(f,ver){var t=tgt();"
"if(!t){$('msg-r').textContent='no writable target slot';return}"
"if(!confirm('Restore factory '+ver+' to '+t.name+'?\\nThis ERASES its "
"current contents ('+t.cur+').'))return;"
"startJob('/restore/factory','file='+encodeURIComponent(f)+"
"'&slot='+t.slot,'msg-r')}"
"function uploadFw(){var fi=$('fwfile');"
"if(!fi.files||!fi.files.length){"
"$('msg-up').textContent='choose a .fw file';return}"
"var fd=new FormData();fd.append('file',fi.files[0]);"
"$('msg-up').textContent='uploading\\u2026';"
"fetch('/update/upload',{method:'POST',body:fd})"
".then(function(r){return r.json()}).then(function(j){"
"if(j.ok){$('msg-up').textContent='uploaded '+(j.version||'')+"
"' ('+j.signature+')';loadSlots()}"
"else $('msg-up').textContent=j.error||'upload failed'})"
".catch(function(){$('msg-up').textContent='upload failed'})}"
"document.addEventListener('click',function(e){"
"var t=e.target,v;if(!t||!t.getAttribute)return;"
"if((v=t.getAttribute('data-boot')))bootTo(v,0);"
"else if((v=t.getAttribute('data-apply')))applyStaged(v,"
"t.getAttribute('data-ver'));"
"else if((v=t.getAttribute('data-restore')))restoreArch(v,"
"t.getAttribute('data-ver'))});"

/* boot + polling */
"function loadMach(){fetch('/status').then(function(r)"
"{return r.json()}).then(function(m){M=m;"
"locked=!!(M.state&&M.state!=='idle')||!!M.diag;lockApply();"
"renderMotion();renderCooling();renderSwitches()}).catch(function(){})}"
"function loadCam(){fetch('/cam/status').then(function(r)"
"{return r.json()}).then(function(s){CS=s;renderStat()})"
".catch(function(){})}"
"fetch('/settings').then(function(r){return r.json()})"
".then(function(s){S=s;fill()}).catch(function(){});"
"loadMach();setInterval(loadMach,2500);"
"loadCam();setInterval(loadCam,5000);"
"loadDiag();setInterval(loadDiag,2500);"
"loadSlots();jobPoll();"
"renderGrbl();tab();refreshSnap();"
"</script></body></html>";
